# Generated by Django 5.1 on 2024-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(max_length=8)),
                ('Longetude', models.FloatField(max_length=8)),
                ('Altitude', models.FloatField(max_length=6)),
                ('HorarioESP', models.FloatField(max_length=8)),
                ('VelocidadeKM', models.FloatField(max_length=6)),
                ('Satelites', models.IntegerField(max_length=3)),
            ],
        ),
    ]
