# Generated by Django 5.1 on 2024-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Satelites',
            field=models.IntegerField(),
        ),
    ]
