# Generated by Django 5.1 on 2024-08-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreador', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Horario',
            field=models.FloatField(),
        ),
    ]
