# Generated by Django 5.1 on 2024-08-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rastreador', '0002_alter_data_satelites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Altitude',
        ),
        migrations.RemoveField(
            model_name='data',
            name='HorarioESP',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Satelites',
        ),
        migrations.RemoveField(
            model_name='data',
            name='VelocidadeKM',
        ),
    ]
