# Generated by Django 5.1 on 2024-08-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rastreador', '0003_remove_data_altitude_remove_data_horarioesp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Longetude',
            new_name='Longitude',
        ),
    ]
